name: RandomnessWaves
favicon: null
layout_spectrum: 0.4228878964204341
typography_spectrum: 0.6839311697985977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3641972753684968
  lightness: 0.6560619869269431
  saturation: 0.711194958537817
  rhythmicContrast: 0.7854618369601667
purpose: []
